// 120 genuine 3D scene / animation presets (12 scene families × 10 variants).
// Kind: "webgl-3d" — real geometry rendered by the bundled WebGL2 engine
// (shared/fx3d). Each variant changes structure (geometry, layout, motion
// path, camera or lighting), not just colour.
import { P } from './params.js';

const SPEED = (d) => P.range('speed', 0, 2, 0.05, d);
const CAM = (d, opts = ['front', 'low', 'three-quarter', 'top', 'orbit']) => P.select('camera', opts, d);

const FAMILIES = {
  tileWave: {
    name: 'Ceramic tile wave', uses: ['hero', 'storefront identity'], perf: 'medium',
    schema: (d) => [P.select('wave', ['radial', 'diagonal', 'ripple', 'rows', 'noise', 'columns'], d.wave), P.range('cols', 8, 40, 1, d.cols), P.range('rows', 3, 16, 1, d.rows),
      P.select('tile', ['vertical', 'square', 'brick'], d.tile), P.range('amplitude', 0, 1, 0.05, d.amplitude), SPEED(d.speed), CAM(d.camera, ['front', 'low', 'three-quarter']),
      P.bool('sign', d.sign), P.bool('glowSweep', d.glowSweep)],
    variants: [
      ['Storefront ripple', { wave: 'ripple', cols: 22, rows: 6, tile: 'vertical', amplitude: 0.35, speed: 0.6, camera: 'front', sign: true, glowSweep: true }],
      ['Diagonal swell', { wave: 'diagonal', cols: 24, rows: 8, tile: 'vertical', amplitude: 0.5, speed: 0.5, camera: 'three-quarter', sign: true, glowSweep: false }],
      ['Radial breath', { wave: 'radial', cols: 18, rows: 8, tile: 'square', amplitude: 0.4, speed: 0.4, camera: 'front', sign: false, glowSweep: true }],
      ['Row cascade', { wave: 'rows', cols: 28, rows: 5, tile: 'brick', amplitude: 0.6, speed: 0.8, camera: 'low', sign: true, glowSweep: false }],
      ['Noise field', { wave: 'noise', cols: 32, rows: 10, tile: 'square', amplitude: 0.3, speed: 0.3, camera: 'three-quarter', sign: false, glowSweep: false }],
      ['Column pulse', { wave: 'columns', cols: 16, rows: 7, tile: 'vertical', amplitude: 0.55, speed: 0.7, camera: 'front', sign: true, glowSweep: false }],
      ['Low angle ripple', { wave: 'ripple', cols: 30, rows: 12, tile: 'vertical', amplitude: 0.25, speed: 0.45, camera: 'low', sign: false, glowSweep: true }],
      ['Brick diagonal', { wave: 'diagonal', cols: 20, rows: 10, tile: 'brick', amplitude: 0.45, speed: 0.6, camera: 'front', sign: false, glowSweep: true }],
      ['Calm wall', { wave: 'radial', cols: 12, rows: 4, tile: 'vertical', amplitude: 0.15, speed: 0.2, camera: 'front', sign: true, glowSweep: false }],
      ['Dense noise', { wave: 'noise', cols: 40, rows: 16, tile: 'vertical', amplitude: 0.2, speed: 0.5, camera: 'low', sign: true, glowSweep: true }],
    ],
  },
  pasta: {
    name: 'Pasta bowl turntable', uses: ['hero', 'item detail', 'promo'], perf: 'medium',
    schema: (d) => [P.select('recipe', ['alfredo', 'pesto', 'mex', 'bolognese'], d.recipe), CAM(d.camera, ['orbit', 'low', 'three-quarter', 'top']), SPEED(d.speed),
      P.range('explode', 0, 1, 0.05, d.explode), P.select('plate', ['paper', 'board', 'none'], d.plate), P.select('light', ['warm', 'studio', 'neon'], d.light)],
    variants: [
      ['Alfredo spin', { recipe: 'alfredo', camera: 'orbit', speed: 0.5, explode: 0, plate: 'paper', light: 'warm' }],
      ['Bowl hero three-quarter', { recipe: 'alfredo', camera: 'three-quarter', speed: 0.35, explode: 0, plate: 'board', light: 'warm' }],
      ['Pesto three-quarter', { recipe: 'pesto', camera: 'three-quarter', speed: 0.6, explode: 0.1, plate: 'paper', light: 'studio' }],
      ['Bolognese studio', { recipe: 'bolognese', camera: 'orbit', speed: 0.3, explode: 0, plate: 'none', light: 'studio' }],
      ['Top-down bowl', { recipe: 'mex', camera: 'top', speed: 0.4, explode: 0, plate: 'paper', light: 'warm' }],
      ['Opened layers', { recipe: 'alfredo', camera: 'three-quarter', speed: 0.25, explode: 0.6, plate: 'none', light: 'studio' }],
      ['Night turntable', { recipe: 'bolognese', camera: 'low', speed: 0.7, explode: 0, plate: 'board', light: 'neon' }],
      ['Slow warm orbit', { recipe: 'pesto', camera: 'orbit', speed: 0.15, explode: 0, plate: 'board', light: 'warm' }],
      ['Floating layers', { recipe: 'mex', camera: 'orbit', speed: 0.45, explode: 0.35, plate: 'none', light: 'neon' }],
      ['Still studio', { recipe: 'alfredo', camera: 'low', speed: 0, explode: 0, plate: 'paper', light: 'studio' }],
    ],
  },
  stack: {
    name: 'Plate build', uses: ['hero', 'launch campaign'], perf: 'medium',
    schema: (d) => [P.select('mode', ['breathe', 'drop-in', 'spiral', 'pop', 'slice'], d.mode), P.select('recipe', ['alfredo', 'pesto', 'mex', 'bolognese'], d.recipe), P.range('spacing', 0.1, 1.5, 0.05, d.spacing), SPEED(d.speed), CAM(d.camera, ['front', 'three-quarter', 'low'])],
    variants: [
      ['Breathing plate', { mode: 'breathe', recipe: 'alfredo', spacing: 0.4, speed: 0.5, camera: 'three-quarter' }],
      ['Drop in', { mode: 'drop-in', recipe: 'bolognese', spacing: 0.6, speed: 0.6, camera: 'front' }],
      ['Spiral build', { mode: 'spiral', recipe: 'pesto', spacing: 0.5, speed: 0.4, camera: 'three-quarter' }],
      ['Pop apart', { mode: 'pop', recipe: 'mex', spacing: 0.8, speed: 0.7, camera: 'low' }],
      ['Slice view', { mode: 'slice', recipe: 'alfredo', spacing: 1, speed: 0.3, camera: 'front' }],
      ['Low breathe', { mode: 'breathe', recipe: 'pesto', spacing: 0.25, speed: 0.35, camera: 'low' }],
      ['Fast drop', { mode: 'drop-in', recipe: 'mex', spacing: 0.4, speed: 1.2, camera: 'three-quarter' }],
      ['Wide spiral', { mode: 'spiral', recipe: 'bolognese', spacing: 1.2, speed: 0.5, camera: 'front' }],
      ['Gentle pop', { mode: 'pop', recipe: 'alfredo', spacing: 0.3, speed: 0.3, camera: 'three-quarter' }],
      ['Tall slice', { mode: 'slice', recipe: 'pesto', spacing: 1.4, speed: 0.5, camera: 'low' }],
    ],
  },

  forms: {
    name: 'Floating forms', uses: ['background accent', 'about page', 'offers'], perf: 'light',
    schema: (d) => [P.select('shape', ['spheres', 'cubes', 'tori', 'mixed', 'capsules', 'icosa'], d.shape), P.range('count', 4, 60, 1, d.count), P.range('spread', 1, 6, 0.25, d.spread),
      P.select('drift', ['float', 'orbit', 'bob', 'tumble'], d.drift), P.select('material', ['glaze', 'matte', 'metal'], d.material), SPEED(d.speed)],
    variants: [
      ['Sesame spheres', { shape: 'spheres', count: 24, spread: 3, drift: 'float', material: 'glaze', speed: 0.4 }],
      ['Tile cubes', { shape: 'cubes', count: 18, spread: 3.5, drift: 'tumble', material: 'glaze', speed: 0.5 }],
      ['Onion rings', { shape: 'tori', count: 12, spread: 2.5, drift: 'orbit', material: 'matte', speed: 0.35 }],
      ['Mixed shelf', { shape: 'mixed', count: 30, spread: 4, drift: 'float', material: 'matte', speed: 0.3 }],
      ['Capsule drift', { shape: 'capsules', count: 16, spread: 3, drift: 'bob', material: 'metal', speed: 0.45 }],
      ['Icosa tumble', { shape: 'icosa', count: 10, spread: 2.5, drift: 'tumble', material: 'metal', speed: 0.6 }],
      ['Dense spheres', { shape: 'spheres', count: 60, spread: 5, drift: 'orbit', material: 'matte', speed: 0.25 }],
      ['Floating cubes', { shape: 'cubes', count: 8, spread: 2, drift: 'bob', material: 'matte', speed: 0.3 }],
      ['Metal rings', { shape: 'tori', count: 20, spread: 4, drift: 'tumble', material: 'metal', speed: 0.5 }],
      ['Sparse mixed', { shape: 'mixed', count: 6, spread: 1.5, drift: 'orbit', material: 'glaze', speed: 0.2 }],
    ],
  },
  particles: {
    name: 'Particle field', uses: ['hero atmosphere', 'loader', 'night mode'], perf: 'light',
    schema: (d) => [P.select('kind', ['embers', 'steam', 'sesame', 'dust', 'glow'], d.kind), P.range('count', 50, 3000, 50, d.count), P.select('motion', ['rise', 'swirl', 'drift', 'burst', 'fall'], d.motion), P.range('size', 1, 12, 0.5, d.size), SPEED(d.speed)],
    variants: [
      ['Grill embers', { kind: 'embers', count: 600, motion: 'rise', size: 3, speed: 0.6 }],
      ['Steam', { kind: 'steam', count: 300, motion: 'rise', size: 9, speed: 0.3 }],
      ['Sesame swirl', { kind: 'sesame', count: 400, motion: 'swirl', size: 3, speed: 0.4 }],
      ['Dust drift', { kind: 'dust', count: 1200, motion: 'drift', size: 1.5, speed: 0.2 }],
      ['LED glow', { kind: 'glow', count: 250, motion: 'drift', size: 6, speed: 0.25 }],
      ['Ember burst', { kind: 'embers', count: 900, motion: 'burst', size: 2.5, speed: 0.8 }],
      ['Sesame fall', { kind: 'sesame', count: 500, motion: 'fall', size: 3.5, speed: 0.5 }],
      ['Glow swirl', { kind: 'glow', count: 800, motion: 'swirl', size: 3, speed: 0.35 }],
      ['Heavy steam', { kind: 'steam', count: 600, motion: 'drift', size: 11, speed: 0.15 }],
      ['Dense dust', { kind: 'dust', count: 3000, motion: 'swirl', size: 1, speed: 0.15 }],
    ],
  },
  logo: {
    name: 'Logo sculpture', uses: ['hero', 'loader', 'about page'], perf: 'light',
    schema: (d) => [P.select('arrangement', ['single', 'stack', 'ring', 'grid', 'mirror'], d.arrangement), P.select('motion', ['turntable', 'sway', 'flip', 'float', 'still'], d.motion),
      P.range('bevel', 0, 0.3, 0.01, d.bevel), P.bool('lightSweep', d.lightSweep), P.bool('tileBackdrop', d.tileBackdrop), SPEED(d.speed)],
    variants: [
      ['Sign block', { arrangement: 'single', motion: 'sway', bevel: 0.08, lightSweep: true, tileBackdrop: true, speed: 0.4 }],
      ['Turntable block', { arrangement: 'single', motion: 'turntable', bevel: 0.12, lightSweep: false, tileBackdrop: false, speed: 0.5 }],
      ['Stacked blocks', { arrangement: 'stack', motion: 'float', bevel: 0.06, lightSweep: true, tileBackdrop: false, speed: 0.35 }],
      ['Ring of signs', { arrangement: 'ring', motion: 'turntable', bevel: 0.05, lightSweep: false, tileBackdrop: false, speed: 0.3 }],
      ['Sign grid', { arrangement: 'grid', motion: 'flip', bevel: 0.04, lightSweep: false, tileBackdrop: true, speed: 0.6 }],
      ['Mirror pair', { arrangement: 'mirror', motion: 'sway', bevel: 0.1, lightSweep: true, tileBackdrop: false, speed: 0.4 }],
      ['Flip sign', { arrangement: 'single', motion: 'flip', bevel: 0.15, lightSweep: false, tileBackdrop: true, speed: 0.5 }],
      ['Still with light', { arrangement: 'single', motion: 'still', bevel: 0.2, lightSweep: true, tileBackdrop: true, speed: 0.4 }],
      ['Floating stack', { arrangement: 'stack', motion: 'sway', bevel: 0.02, lightSweep: false, tileBackdrop: true, speed: 0.25 }],
      ['Grid float', { arrangement: 'grid', motion: 'float', bevel: 0.08, lightSweep: true, tileBackdrop: false, speed: 0.3 }],
    ],
  },
  wedges: {
    name: 'Wedges in motion', uses: ['sides category', 'promo', 'empty cart'], perf: 'medium',
    schema: (d) => [P.select('mode', ['fall', 'pile', 'spin', 'fountain', 'orbit'], d.mode), P.range('count', 10, 300, 5, d.count), SPEED(d.speed), P.bool('cup', d.cup)],
    variants: [
      ['Falling wedges', { mode: 'fall', count: 80, speed: 0.6, cup: false }],
      ['Wedge pile', { mode: 'pile', count: 120, speed: 0.3, cup: false }],
      ['Spinning cup', { mode: 'spin', count: 40, speed: 0.5, cup: true }],
      ['Wedge fountain', { mode: 'fountain', count: 100, speed: 0.7, cup: true }],
      ['Wedge orbit', { mode: 'orbit', count: 60, speed: 0.4, cup: true }],
      ['Light rain', { mode: 'fall', count: 30, speed: 0.4, cup: true }],
      ['Big pile', { mode: 'pile', count: 300, speed: 0.2, cup: true }],
      ['Slow spin', { mode: 'spin', count: 25, speed: 0.2, cup: true }],
      ['Burst fountain', { mode: 'fountain', count: 220, speed: 1.1, cup: false }],
      ['Wide orbit', { mode: 'orbit', count: 150, speed: 0.25, cup: false }],
    ],
  },
  material: {
    name: 'Material study', uses: ['about page', 'brand moments'], perf: 'light',
    schema: (d) => [P.select('geometry', ['sphere', 'torus', 'knot', 'box', 'cylinder'], d.geometry), P.select('material', ['glazed tile', 'tomato lacquer', 'brushed steel', 'wax paper', 'ceramic'], d.material),
      P.range('lightOrbit', 0, 2, 0.05, d.lightOrbit), P.bool('rim', d.rim), SPEED(d.speed)],
    variants: [
      ['Glazed sphere', { geometry: 'sphere', material: 'glazed tile', lightOrbit: 0.5, rim: true, speed: 0.3 }],
      ['Lacquer torus', { geometry: 'torus', material: 'tomato lacquer', lightOrbit: 0.3, rim: true, speed: 0.4 }],
      ['Steel knot', { geometry: 'knot', material: 'brushed steel', lightOrbit: 0.6, rim: false, speed: 0.5 }],
      ['Paper box', { geometry: 'box', material: 'wax paper', lightOrbit: 0.2, rim: false, speed: 0.3 }],
      ['Ceramic cylinder', { geometry: 'cylinder', material: 'ceramic', lightOrbit: 0.4, rim: true, speed: 0.25 }],
      ['Lacquer knot', { geometry: 'knot', material: 'tomato lacquer', lightOrbit: 0.8, rim: true, speed: 0.6 }],
      ['Tile box', { geometry: 'box', material: 'glazed tile', lightOrbit: 0.5, rim: false, speed: 0.35 }],
      ['Steel sphere', { geometry: 'sphere', material: 'brushed steel', lightOrbit: 1.2, rim: true, speed: 0.2 }],
      ['Ceramic torus', { geometry: 'torus', material: 'ceramic', lightOrbit: 0.3, rim: false, speed: 0.45 }],
      ['Paper cylinder', { geometry: 'cylinder', material: 'wax paper', lightOrbit: 0.7, rim: true, speed: 0.3 }],
    ],
  },
  lights: {
    name: 'Light sweep', uses: ['hero', 'night mode'], perf: 'medium',
    schema: (d) => [P.select('scene', ['tile-wall', 'sign', 'counter'], d.scene), P.range('lights', 1, 4, 1, d.lights), P.select('palette', ['glow', 'warm', 'mixed'], d.palette),
      P.select('sweep', ['horizontal', 'vertical', 'circle', 'flicker'], d.sweep), SPEED(d.speed)],
    variants: [
      ['Wall scan', { scene: 'tile-wall', lights: 1, palette: 'glow', sweep: 'horizontal', speed: 0.5 }],
      ['Sign spotlight', { scene: 'sign', lights: 1, palette: 'warm', sweep: 'circle', speed: 0.4 }],
      ['Counter glow', { scene: 'counter', lights: 2, palette: 'mixed', sweep: 'horizontal', speed: 0.3 }],
      ['Neon flicker', { scene: 'sign', lights: 2, palette: 'glow', sweep: 'flicker', speed: 0.8 }],
      ['Vertical wash', { scene: 'tile-wall', lights: 3, palette: 'mixed', sweep: 'vertical', speed: 0.35 }],
      ['Warm circle', { scene: 'counter', lights: 1, palette: 'warm', sweep: 'circle', speed: 0.25 }],
      ['Twin scan', { scene: 'tile-wall', lights: 2, palette: 'glow', sweep: 'horizontal', speed: 0.7 }],
      ['Four corners', { scene: 'sign', lights: 4, palette: 'mixed', sweep: 'circle', speed: 0.3 }],
      ['Counter flicker', { scene: 'counter', lights: 3, palette: 'glow', sweep: 'flicker', speed: 0.5 }],
      ['Slow wash', { scene: 'tile-wall', lights: 1, palette: 'warm', sweep: 'vertical', speed: 0.15 }],
    ],
  },
  cards: {
    name: 'Spatial menu cards', uses: ['menu highlight', 'offers', 'hero'], perf: 'medium',
    schema: (d) => [P.select('layout', ['ring', 'helix', 'fan', 'grid', 'stack'], d.layout), P.range('cards', 3, 16, 1, d.cards), P.range('tilt', 0, 45, 1, d.tilt), SPEED(d.speed)],
    variants: [
      ['Card ring', { layout: 'ring', cards: 8, tilt: 10, speed: 0.3 }],
      ['Helix', { layout: 'helix', cards: 12, tilt: 5, speed: 0.4 }],
      ['Fan', { layout: 'fan', cards: 5, tilt: 20, speed: 0.3 }],
      ['Floating grid', { layout: 'grid', cards: 9, tilt: 15, speed: 0.25 }],
      ['Deck stack', { layout: 'stack', cards: 6, tilt: 30, speed: 0.4 }],
      ['Big ring', { layout: 'ring', cards: 16, tilt: 0, speed: 0.2 }],
      ['Tight helix', { layout: 'helix', cards: 6, tilt: 25, speed: 0.6 }],
      ['Wide fan', { layout: 'fan', cards: 9, tilt: 8, speed: 0.2 }],
      ['Tilted grid', { layout: 'grid', cards: 4, tilt: 40, speed: 0.35 }],
      ['Tall stack', { layout: 'stack', cards: 12, tilt: 12, speed: 0.3 }],
    ],
  },
  paper: {
    name: 'Paper sheet', uses: ['menu header', 'about page', 'packaging moments'], perf: 'light',
    schema: (d) => [P.select('mode', ['wave', 'fold', 'ripple', 'flutter', 'crumple'], d.mode), P.range('segments', 8, 80, 2, d.segments), P.range('amplitude', 0, 1, 0.05, d.amplitude), P.bool('wordmark', d.wordmark), SPEED(d.speed)],
    variants: [
      ['Gentle wave', { mode: 'wave', segments: 40, amplitude: 0.3, wordmark: true, speed: 0.4 }],
      ['Corner fold', { mode: 'fold', segments: 32, amplitude: 0.6, wordmark: true, speed: 0.3 }],
      ['Ripple', { mode: 'ripple', segments: 60, amplitude: 0.25, wordmark: true, speed: 0.5 }],
      ['Flutter', { mode: 'flutter', segments: 24, amplitude: 0.5, wordmark: false, speed: 0.8 }],
      ['Crumple', { mode: 'crumple', segments: 40, amplitude: 0.4, wordmark: true, speed: 0.3 }],
      ['Plain wave', { mode: 'wave', segments: 20, amplitude: 0.6, wordmark: false, speed: 0.3 }],
      ['Deep fold', { mode: 'fold', segments: 48, amplitude: 1, wordmark: false, speed: 0.2 }],
      ['Fine ripple', { mode: 'ripple', segments: 80, amplitude: 0.15, wordmark: false, speed: 0.6 }],
      ['Branded flutter', { mode: 'flutter', segments: 36, amplitude: 0.35, wordmark: true, speed: 0.5 }],
      ['Soft crumple', { mode: 'crumple', segments: 24, amplitude: 0.2, wordmark: false, speed: 0.2 }],
    ],
  },
  ingredients: {
    name: 'Ingredient orbit', uses: ['hero', 'item detail', 'campaigns'], perf: 'medium',
    schema: (d) => [P.select('set', ['penne', 'tomatoes', 'cheese', 'basil', 'mixed'], d.set), P.select('orbit', ['ring', 'atom', 'spiral', 'swarm', 'layers'], d.orbit), P.range('count', 4, 80, 1, d.count), SPEED(d.speed), P.bool('bowl', d.bowl)],
    variants: [
      ['Penne ring', { set: 'penne', orbit: 'ring', count: 12, speed: 0.4, bowl: true }],
      ['Tomato atom', { set: 'tomatoes', orbit: 'atom', count: 9, speed: 0.5, bowl: true }],
      ['Cheese spiral', { set: 'cheese', orbit: 'spiral', count: 16, speed: 0.35, bowl: true }],
      ['Basil swarm', { set: 'basil', orbit: 'swarm', count: 40, speed: 0.4, bowl: false }],
      ['Mixed layers', { set: 'mixed', orbit: 'layers', count: 24, speed: 0.3, bowl: true }],
      ['Mixed swarm', { set: 'mixed', orbit: 'swarm', count: 80, speed: 0.25, bowl: false }],
      ['Tomato ring', { set: 'tomatoes', orbit: 'ring', count: 18, speed: 0.6, bowl: false }],
      ['Penne spiral', { set: 'penne', orbit: 'spiral', count: 30, speed: 0.5, bowl: true }],
      ['Cheese layers', { set: 'cheese', orbit: 'layers', count: 12, speed: 0.2, bowl: true }],
      ['Basil atom', { set: 'basil', orbit: 'atom', count: 6, speed: 0.7, bowl: true }],
    ],
  },
};

export const THREE_PRESETS = Object.entries(FAMILIES).flatMap(([fam, f]) => f.variants.map(([name, d], i) => ({
  id: `3d-${fam.toLowerCase()}-${String(i + 1).padStart(2, '0')}`,
  name: `${f.name}: ${name}`,
  category: '3d',
  family: fam,
  kind: 'webgl-3d',
  renderer: 'WebGL2 real-time 3D (bundled engine, no external library)',
  params: f.schema(d),
  uses: f.uses,
  perf: f.perf,
  reducedMotion: 'Renders a single still frame; static CSS art if WebGL is unavailable or the device is low-power.',
  description: `${f.name} — ${name.toLowerCase()}.`,
})));

export const THREE_FAMILIES = Object.fromEntries(Object.entries(FAMILIES).map(([k, f]) => [k, f.name]));
